.TH RPM-NAME 1 "DATE" Linux "User Manuals"
.SH NAME
<rpm-name> \- <rpm description>
.SH FILES
.B executable.1
| 
.B executable.2
| 
.B main-conf-file
.SH FILE DESCRIPTION
.IP "executable.1"
Does something...
.IP "executable.2"
Does something else...
.IP "main-conf-file"
Configure it here...
.SH EXAMPLE USAGE
.IP "1)"
Run X.
.IP "2)"
Run Y.
.SH AUTHOR
Organization_Name - (Name <Email Address>, Name <Email Address>)
